Repository Quantit-Github/qui-react, pull requests merged in 2023-10, with the labels that each got.

#38 PQ-50 체크박스 컴포넌트
  apps/docs/stories/Checkbox.stories.tsx
  packages/qui-core/src/components/Checkbox/CheckIcon.tsx
  packages/qui-core/src/components/Checkbox/IndeterminateIcon.tsx
  packages/qui-core/src/components/Checkbox/index.tsx
  packages/qui-core/src/components/Checkbox/type.d.ts
  packages/qui-core/src/components/index.tsx
  packages/qui-core/src/styles/tokens/state-overlay/state-overlay.token.util.ts
  packages/qui-core/src/styles/tokens/switch/checkbox.token.ts
  packages/qui-core/src/styles/tokens/switch/checkbox.token.util.ts
  packages/qui-core/src/styles/tokens/switch/index.ts
Labels: feature

#41 PQ-83 드롭다운 컴포넌트
  apps/docs/stories/Dropdown.stories.tsx
  packages/qui-core/src/components/Dropdown/ChevronDownIcon.tsx
  packages/qui-core/src/components/Dropdown/ChevronRightIcon.tsx
  packages/qui-core/src/components/Dropdown/ChevronUpIcon.tsx
  packages/qui-core/src/components/Dropdown/DropdownList.tsx
  packages/qui-core/src/components/Dropdown/index.tsx
  packages/qui-core/src/components/Dropdown/type.d.ts
  packages/qui-core/src/components/index.tsx
  packages/qui-core/src/styles/tokens/dropdown/dropdown.token.ts
  packages/qui-core/src/styles/tokens/dropdown/dropdown.token.util.ts
  packages/qui-core/src/styles/tokens/dropdown/index.ts
  packages/qui-core/src/styles/tokens/item-list/index.ts
  packages/qui-core/src/styles/tokens/item-list/item-list.token.ts
  packages/qui-core/src/styles/tokens/scrollbar/index.ts
  packages/qui-core/src/styles/tokens/scrollbar/scrollbar.token.ts
Labels: feature

#46 PQ-114 아이콘 폴더 분리
  apps/docs/stories/Dropdown.stories.tsx
  packages/qui-core/src/assets/icons/CheckIcon.tsx
  packages/qui-core/src/assets/icons/ChevronDownIcon.tsx
  packages/qui-core/src/assets/icons/ChevronRightIcon.tsx
  packages/qui-core/src/assets/icons/ChevronUpIcon.tsx
  packages/qui-core/src/assets/icons/IndeterminateIcon.tsx
  packages/qui-core/src/components/Checkbox/index.tsx
  packages/qui-core/src/components/Dropdown/DropdownList.tsx
  packages/qui-core/src/components/Dropdown/index.tsx
Labels: refactor

#44 PQ-86 탭 컴포넌트
  apps/docs/stories/Tab.stories.tsx
  packages/qui-core/src/components/Tab/TabItemList.tsx
  packages/qui-core/src/components/Tab/index.tsx
  packages/qui-core/src/components/Tab/type.d.ts
  packages/qui-core/src/components/index.tsx
  packages/qui-core/src/styles/tokens/tab/index.ts
  packages/qui-core/src/styles/tokens/tab/tab.token.ts
  packages/qui-core/src/styles/tokens/tab/tab.token.util.ts
  pnpm-lock.yaml
Labels: feature

#47 PQ-107 페이지네이션 컴포넌트
  apps/docs/stories/Pagination.stories.tsx
  packages/qui-core/src/assets/icons/ChevronLeftIcon.tsx
  packages/qui-core/src/assets/icons/ChevronRightIcon.tsx
  packages/qui-core/src/components/Pagination/index.tsx
  packages/qui-core/src/components/Pagination/type.d.ts
  packages/qui-core/src/components/index.tsx
  packages/qui-core/src/styles/styled.d.ts
  packages/qui-core/src/styles/theme/size.type.d.ts
  packages/qui-core/src/styles/theme/size.util.ts
  packages/qui-core/src/styles/tokens/button/button.token.ts
  packages/qui-core/src/styles/tokens/pagination/index.ts
  packages/qui-core/src/styles/tokens/pagination/pagination.token.util.ts
  packages/qui-core/src/styles/tokens/tab/tab.token.ts
  packages/qui-core/src/styles/tokens/tab/tab.token.util.ts
Labels: feature

#48 Nakhun/pq 112
  apps/docs/stories/Button.stories.tsx
  apps/docs/stories/ButtonIcon.stories.tsx
  apps/qui-test/src/App.tsx
  packages/qui-core/README.md
  packages/qui-core/package.json
  packages/qui-core/src/assets/icons/SmileIcon.tsx
  packages/qui-core/src/components/Button.tsx
  packages/qui-core/src/components/Button/IconButton.tsx
  packages/qui-core/src/components/Button/index.tsx
  packages/qui-core/src/components/Button/type.d.ts
  packages/qui-core/src/styles/tokens/button/button.token.type.d.ts
  packages/qui-core/src/styles/tokens/button/button.token.util.ts
  packages/qui-core/src/styles/tokens/state-overlay/state-overlay.token.type.d.ts
  packages/qui-core/src/styles/tokens/state-overlay/state-overlay.token.util.ts
  pnpm-lock.yaml
Labels: feature

#49 NO-ISSUE Tab Token 파일 위치 변경
  packages/qui-core/src/components/Tab/TabItemList.tsx
  packages/qui-core/src/styles/tokens/pagination/pagination.token.util.ts
  packages/qui-core/src/styles/tokens/switch/index.ts
  packages/qui-core/src/styles/tokens/switch/tab.token.ts
  packages/qui-core/src/styles/tokens/switch/tab.token.util.ts
  packages/qui-core/src/styles/tokens/tab/index.ts
Labels: refactor

#50 PQ-122 버튼 border-radius 값 수정
  packages/qui-core/package.json
  packages/qui-core/src/components/Button/index.tsx
Labels: fix

#52 Nakhun/pq 123
  apps/docs/stories/Button.stories.tsx
  packages/qui-core/src/components/Button/index.tsx
  packages/qui-core/src/components/Button/type.d.ts
  packages/qui-core/src/styles/tokens/button/button.token.type.d.ts
  packages/qui-core/src/styles/tokens/button/button.token.util.ts
Labels: bug, refactor
