Repository Quantit-Github/qui-react, pull requests merged in 2023-09, with the labels that each got.

#16 PQ 49 토큰 아키텍쳐 도입
  .changeset/new-worms-smash.md
  .npmrc
  apps/docs/components/index.tsx
  apps/qui-test/package.json
  apps/qui-test/src/App.tsx
  apps/qui-test/src/assets/light.png
  apps/qui-test/src/assets/moon.png
  packages/qui-core/package.json
  packages/qui-core/src/components/Button.tsx
  packages/qui-core/src/components/Typography.tsx
  packages/qui-core/src/styles/QuiThemeProvider.tsx
  packages/qui-core/src/styles/base/base.const.ts
  packages/qui-core/src/styles/base/base.type.ts
  packages/qui-core/src/styles/themes/index.ts
  packages/qui-core/src/styles/themes/palette.const.ts
  packages/qui-core/src/styles/themes/palette.ts
  packages/qui-core/src/styles/themes/palette.type.d.ts
  packages/qui-core/src/styles/themes/palette.utils.ts
  packages/qui-core/src/styles/themes/theme.ts
  packages/qui-core/src/styles/themes/theme.type.d.ts
  packages/qui-core/src/styles/themes/typography.const.ts
  packages/qui-core/src/styles/themes/typography.type.d.ts
  packages/qui-core/src/styles/tokens/button/button-active.token.ts
  packages/qui-core/src/styles/tokens/button/button-disabled.token.ts
  packages/qui-core/src/styles/tokens/button/button.token.d.ts
  packages/qui-core/src/styles/tokens/button/index.ts
  packages/qui-core/src/styles/tokens/index.ts
  packages/qui-core/src/styles/tokens/state-overlay.token.ts
  pnpm-lock.yaml
Labels: feature

#28 PQ-65 타이포그래피 Default Value(CSS String) 세팅
  .gitignore
  packages/qui-core/jest.config.js
  packages/qui-core/package.json
  packages/qui-core/src/components/Typography.tsx
  packages/qui-core/src/styles/themes/index.ts
  packages/qui-core/src/styles/themes/theme.type.d.ts
  packages/qui-core/src/styles/themes/typography.const.ts
  packages/qui-core/src/styles/themes/typography.type.d.ts
  packages/qui-core/src/styles/themes/typography.utils.ts
  packages/qui-core/test/themes.test.ts
  pnpm-lock.yaml
Labels: feature

#29 PQ-67 Theme 시스템 변경
  apps/docs/.storybook/preview.tsx
  apps/docs/stories/Button.stories.tsx
  apps/next-app-test/components/Layout.tsx
  apps/next-app-test/pages/_app.tsx
  apps/next-app-test/pages/index.tsx
  apps/qui-test/src/App.tsx
  packages/qui-core/package.json
  packages/qui-core/src/components/Button.tsx
  packages/qui-core/src/styles/QuiThemeProvider.tsx
  packages/qui-core/src/styles/ThemeProvider.tsx
  packages/qui-core/src/styles/index.ts
  packages/qui-core/src/styles/themes/index.ts
  packages/qui-core/src/styles/themes/palette.ts
  packages/qui-core/src/styles/themes/palette.util.ts
  packages/qui-core/src/styles/themes/theme.const.ts
  packages/qui-core/src/styles/themes/theme.ts
  packages/qui-core/src/styles/themes/theme.type.d.ts
  packages/qui-core/src/styles/themes/typography.const.ts
  packages/qui-core/src/styles/themes/typography.util.ts
  packages/qui-core/src/styles/tokens/button/button-active.token.ts
  packages/qui-core/src/styles/tokens/button/button-disabled.token.ts
  packages/qui-core/src/styles/tokens/state-overlay.token.ts
  packages/qui-core/test/themes.test.ts
Labels: refactor

#31 PQ-71 README 작성
  README.md
  apps/docs/package.json
  apps/next-app-test/.babelrc
  apps/next-app-test/components/Layout.tsx
  apps/next-app-test/package.json
  apps/next-app-test/styled.d.ts
  packages/qui-core/README.md
  packages/qui-core/package.json
  pnpm-lock.yaml
Labels: documentation

#32 PQ-73 Next.js 스타일 컴포넌트 클래스명 동기화 처리 안되는 문제 수정
  packages/qui-core/package.json
  packages/qui-core/src/styles/ThemeProvider.tsx
Labels: bug

#33 PQ-46 토글 컴포넌트 구현
  apps/docs/stories/Toggle.stories.tsx
  packages/qui-core/package.json
  packages/qui-core/src/components/Toggle.tsx
  packages/qui-core/src/components/index.tsx
Labels: feature

#34 PQ-76 토큰의 다크, 라이트 테마를 단일값으로 처리하도록 변경
  packages/qui-core/package.json
  packages/qui-core/src/styles/themes/palette.const.ts
  packages/qui-core/src/styles/themes/palette.type.d.ts
  packages/qui-core/src/styles/tokens/button/button-active.token.ts
  packages/qui-core/src/styles/tokens/button/button-common.token.ts
  packages/qui-core/src/styles/tokens/button/button-disabled.token.ts
  packages/qui-core/src/styles/tokens/button/index.ts
  packages/qui-core/src/styles/tokens/state-overlay.token.ts
Labels: refactor

#35 PQ-47 토글 토큰 구현
  apps/docs/stories/Button.stories.tsx
  apps/docs/stories/Toggle.stories.tsx
  packages/qui-core/package.json
  packages/qui-core/src/components/Toggle.tsx
  packages/qui-core/src/components/index.tsx
  packages/qui-core/src/styles/themes/palette.const.ts
  packages/qui-core/src/styles/tokens/index.ts
  packages/qui-core/src/styles/tokens/switch/common.token.ts
  packages/qui-core/src/styles/tokens/switch/toggle.token.ts
Labels: feature

#36 PQ-91 토큰 구조 변경
  apps/docs/stories/Toggle.stories.tsx
  apps/next-app-test/components/Layout.tsx
  packages/qui-core/package.json
  packages/qui-core/src/components/Button.tsx
  packages/qui-core/src/components/Toggle.tsx
  packages/qui-core/src/styles/tokens/button/button-active.token.ts
  packages/qui-core/src/styles/tokens/button/button-common.token.ts
  packages/qui-core/src/styles/tokens/button/button.token.ts
  packages/qui-core/src/styles/tokens/button/button.token.type.d.ts
  packages/qui-core/src/styles/tokens/button/button.token.util.ts
  packages/qui-core/src/styles/tokens/button/common.token.ts
  packages/qui-core/src/styles/tokens/button/index.ts
  packages/qui-core/src/styles/tokens/index.ts
  packages/qui-core/src/styles/tokens/state-overlay/index.ts
  packages/qui-core/src/styles/tokens/state-overlay/state-overlay.token.ts
  packages/qui-core/src/styles/tokens/state-overlay/state-overlay.token.util.ts
  packages/qui-core/src/styles/tokens/switch/common.token.ts
  packages/qui-core/src/styles/tokens/switch/index.ts
  packages/qui-core/src/styles/tokens/switch/toggle.token.ts
  packages/qui-core/src/styles/tokens/switch/toggle.token.util.ts
Labels: refactor

#37 PQ-95 Divider 컴포넌트 구현
  apps/docs/stories/Divider.stories.tsx
  packages/qui-core/src/components/Divider.tsx
  packages/qui-core/src/components/index.tsx
  packages/qui-core/src/styles/tokens/divider/divider.token.ts
  packages/qui-core/src/styles/tokens/divider/divider.token.type.d.ts
  packages/qui-core/src/styles/tokens/divider/index.ts
  packages/qui-core/src/styles/tokens/index.ts
Labels: feature
