Repository Quantit-Github/qui-react, pull requests merged in 2023-11, with the labels that each got.

#53 Hyd/pq 125
  apps/docs/stories/Checkbox.stories.tsx
  apps/docs/stories/Dropdown.stories.tsx
  packages/qui-core/src/assets/icons/CheckIcon.tsx
  packages/qui-core/src/assets/icons/ChevronDownIcon.tsx
  packages/qui-core/src/assets/icons/ChevronLeftIcon.tsx
  packages/qui-core/src/assets/icons/ChevronRightIcon.tsx
  packages/qui-core/src/assets/icons/ChevronUpIcon.tsx
  packages/qui-core/src/assets/icons/ExternalLinkIcon.tsx
  packages/qui-core/src/assets/icons/IndeterminateIcon.tsx
  packages/qui-core/src/assets/icons/SmileIcon.tsx
  packages/qui-core/src/assets/icons/index.tsx
  packages/qui-core/src/components/Button/IconButton.tsx
  packages/qui-core/src/components/Button/type.d.ts
  packages/qui-core/src/components/Checkbox/index.tsx
  packages/qui-core/src/components/Checkbox/type.d.ts
  packages/qui-core/src/components/Dropdown/DropdownList.tsx
  packages/qui-core/src/components/Dropdown/index.tsx
  packages/qui-core/src/components/Pagination/index.tsx
  packages/qui-core/src/components/Tab/TabItemList.tsx
  packages/qui-core/src/styles/tokens/index.ts
  packages/qui-core/src/styles/tokens/switch/checkbox.token.util.ts
Labels: fix

#54 PQ-127 스토리북 argTypes 활용 예시 작성
  apps/docs/stories/ButtonIcon.stories.tsx
  apps/qui-test/src/App.tsx
  packages/qui-core/src/assets/icons/SmileIcon.tsx
  packages/qui-core/src/components/Button/IconButton.tsx
  packages/qui-core/src/components/Button/index.tsx
  packages/qui-core/src/components/Button/type.d.ts
Labels: fix

#57 PQ-133 디바이더 컴포넌트 이름 변경
  apps/docs/stories/Divider.stories.tsx
  packages/qui-core/src/components/Divider.tsx
  packages/qui-core/src/styles/tokens/divider/divider.token.type.d.ts
Labels: refactor

#59 NO-ISSUE 아코디언 컴포넌트 Title Props 임시 수정
  apps/docs/stories/Accordion.stories.tsx
  packages/qui-core/src/components/Accordion/type.d.ts
Labels: refactor

#60 NO-ISSUE 버전 업데이트
  packages/qui-core/package.json
Labels: refactor

#62 PQ-130 탭 컴포넌트 수정
  apps/docs/stories/Tab.stories.tsx
  packages/qui-core/src/components/Tab/TabItemList.tsx
  packages/qui-core/src/components/Tab/index.tsx
  packages/qui-core/src/components/Tab/type.d.ts
  packages/qui-core/src/styles/tokens/switch/tab.token.util.ts
Labels: refactor, fix
